<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/12/22 11:18:04
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 2,
  'app_max_jobs_on_category' => 20,
));
